from typing import Any, Generic

from .run import TContext, RunContextWrapper
from .agent import Agent
from .tool import Tool
# --------------------------------------------------------------------------------
# AgentHooks: 建模agent的生命周期
# --------------------------------------------------------------------------------
# 提供了 agent/tool 两种粒度的 hook
class AgentHooks(Generic[TContext]):
    async def on_start(self, context: RunContextWrapper[TContext], agent: Agent[TContext]) -> None: ...
    async def on_end(self, context: RunContextWrapper[TContext], agent: Agent[TContext], output: Any) -> None: ...
    async def on_handoff(self, context: RunContextWrapper[TContext], agent: Agent[TContext], source: Agent[TContext]) -> None: ...
    async def on_tool_start(self, context: RunContextWrapper[TContext], agent: Agent[TContext], tool: Tool) -> None: ...
    async def on_tool_end(self, context: RunContextWrapper[TContext], agent: Agent[TContext], tool: Tool, result: str) -> None: ...

# 相较于 AgentHooks, 仅仅 on_handoff 参数多了 from_agent 和 to_agent
class RunHooks(Generic[TContext]):
    async def on_agent_start(self, context: RunContextWrapper[TContext], agent: Agent[TContext]) -> None: ...
    async def on_agent_end(self, context: RunContextWrapper[TContext], agent: Agent[TContext], output: Any) -> None: ...
    async def on_handoff(self, context: RunContextWrapper[TContext], agent: Agent[TContext], from_agent: Agent[TContext], to_agent: Agent[TContext]) -> None: ...
    async def on_tool_start(self, context: RunContextWrapper[TContext], agent: Agent[TContext], tool: Tool) -> None: ...
    async def on_tool_end(self, context: RunContextWrapper[TContext], agent: Agent[TContext], tool: Tool, result: str) -> None: ...

