import abc
from typing import Any, Generic

from typing_extensions import TypedDict, TypeVar

""" --------------------------------------------------------------------------------------------------------------------
Tracing
-------------------------------------------------------------------------------------------------------------------- """
TSpanData = TypeVar("TSpanData", bound=SpanData)

class Span(abc.ABC, Generic[TSpanData]):
    def trace_id(self) -> str: ...
    def span_id(self) -> str: ...
    def span_data(self) -> TSpanData: ...
    def start(self, mark_as_current: bool = False): ...
    def finish(self, reset_current: bool = False) -> None: ...
    def __enter__(self) -> Span[TSpanData]: ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def parent_id(self) -> str | None: ...
    def set_error(self, error: SpanError) -> None: ...
    def error(self) -> SpanError | None: ...
    def export(self) -> dict[str, Any] | None: ...
    def started_at(self) -> str | None: ...
    def ended_at(self) -> str | None: ...

class SpanError(TypedDict):
    message: str
    data: dict[str, Any] | None

class SpanData(abc.ABC):
    def export(self) -> dict[str, Any]: ...
    def type(self) -> str: ...
